#!/bin/sh
svn up || exit 1
echo "#define TUXANCI_VERSION \"svn$(( `svn info | grep Revision |awk -F ': ' '{print $2}'` + 1 ))\"" > ./config.h
if [ $# -eq "0" ]; then
	svn ci
	exit 0
fi
while getopts :F:m: arg; do
	case $arg in
		F) svn ci -F "${OPTARG}";;
		m) svn ci -m "\"${OPTARG}\"";;
		*) svn ci;;
	esac
done
