.\" The Tuxanci man page.
.\" Contact tomas.chvatal@gmail.com to correct errors or omissions.
.TH man 6 "24 December 2008" "1.0" "Tuxanci man page"
.SH NAME
tuxanci - Tuxanci is first tux shooter inspired by game Bulanci.

.SH AUTHOR
.nf
Dušan Ďurech (Oroborus) <dusan.d@centrum.sk>
Jiří Helebrant (helb) <helb@helb.cz>
Michal Zima (xHire) <xhire@tuxportal.cz>
Tomáš Chvátal (scarab) <tomas.chvatal@gmail.com>
Roman Kabelka (CJ Neti) <neti@cjneti.net>
Connor Thomson (GNUfault) <bluMATRIKZ@gmail.com>
.fi
.SH HISTORY
2026-02 \- Tuxanci 0.22.3
2026-01 \- Tuxanci 0.22.2
2026-01 \- Tuxanci 0.22.1
2026-01 \- Tuxanci 0.22.0
2008-10 \- Tuxanci 0.21.0
2008-08 \- Tuxanci 0.20.0
