
all: arena.o arenaFile.o director.o gun.o homeDirector.o checkFront.o idManager.o item.o index.o list.o main.o modules.o myTimer.o net_multiplayer.o protect.o proto.o server.o shot.o space.o storage.o textFile.o tux.o

arena.o: arena.c arena.h
	$(CC) $(CFLAGS) -o arena.o -c arena.c

arenaFile.o: arenaFile.c arenaFile.h
	$(CC) $(CFLAGS) -o arenaFile.o -c arenaFile.c

director.o: director.c director.h
	$(CC) $(CFLAGS) -o director.o -c director.c

gun.o: gun.c gun.h
	$(CC) $(CFLAGS) -o gun.o -c gun.c

homeDirector.o: homeDirector.c homeDirector.h
	$(CC) $(CFLAGS) -o homeDirector.o -c homeDirector.c

checkFront.o: checkFront.c checkFront.h
	$(CC) $(CFLAGS) -o checkFront.o -c checkFront.c

idManager.o: idManager.c idManager.h
	$(CC) $(CFLAGS) -o idManager.o -c idManager.c

item.o: item.c item.h
	$(CC) $(CFLAGS) -o item.o -c item.c

index.o: index.c index.h
	$(CC) $(CFLAGS) -o index.o -c index.c

list.o: list.c list.h
	$(CC) $(CFLAGS) -o list.o -c list.c

main.o: main.c main.h
	$(CC) $(CFLAGS) -o main.o -c main.c

modules.o: modules.c modules.h
	$(CC) $(CFLAGS) -o modules.o -c modules.c

myTimer.o: myTimer.c myTimer.h
	$(CC) $(CFLAGS) -o myTimer.o -c myTimer.c

net_multiplayer.o: net_multiplayer.c net_multiplayer.h
	$(CC) $(CFLAGS) -o net_multiplayer.o -c net_multiplayer.c

protect.o: protect.c protect.h
	$(CC) $(CFLAGS) -o protect.o -c protect.c

server.o: server.c server.h
	$(CC) $(CFLAGS) -o server.o -c server.c

shot.o: shot.c shot.h
	$(CC) $(CFLAGS) -o shot.o -c shot.c

space.o: space.c space.h
	$(CC) $(CFLAGS) -o space.o -c space.c

storage.o: storage.c storage.h
	$(CC) $(CFLAGS) -o storage.o -c storage.c

textFile.o: textFile.c textFile.h
	$(CC) $(CFLAGS) -o textFile.o -c textFile.c

tux.o: tux.c tux.h
	$(CC) $(CFLAGS) -o tux.o -c tux.c

clean:
	rm -rf *.o


